### ISSUE TITLE
Login events not getting User info + small UI inconsistency 

### ISSUE THREAD

**Issue by JorisOrangeStudio** [mitydigital/statamic-logger#13]
When using database users (not 100% sure if that is causing this issue) the Login events are not able to find the user details. All other events are working as expected with showing the full user details. 
<img width="1072" alt="Screenshot 2024-08-22 at 10 18 48" src="https://github.com/user-attachments/assets/58c1cb6c-5c40-4bbc-ada7-ece7f8c578b5">

Also the styling of the checkboxes looks a bit off:
<img width="770" alt="image" src="https://github.com/user-attachments/assets/d25286da-4893-4c77-b4ed-ae3a6a93ca41">

**Comment by martyf** [comment]
Closed due to inactivity
