### ISSUE TITLE
Multi-line strings written to logs cause error in parsing

### ISSUE THREAD

**Issue by tobimori** [mitydigital/statamic-logger#2]
![CleanShot 2023-12-04 at 23 34 27@2x](https://github.com/mitydigital/statamic-logger/assets/29142128/c8d92605-28e3-4060-a3d8-f4eb6327a205)
I'm logging an error message here with `$e->getMessage()` which contains newlines and those are written to the log as well.

![CleanShot 2023-12-04 at 23 35 14@2x](https://github.com/mitydigital/statamic-logger/assets/29142128/29751139-f25e-4f1c-afc8-202f9bb4ca7e)
However, when loading the Logger view in the panel, it seems to fail loading.

**Comment by martyf** [comment]
Please update to 1.0.3 which resolves this issue.

Your log entry will be preserved on a single line, and it is your responsibility as the developer to ensure line breaks are preserved at the template level as required.
