### ISSUE TITLE
Not generating log files (Call to undefined method App\Models\User::name())

### ISSUE THREAD

**Issue by JorisOrangeStudio** [mitydigital/statamic-logger#7]
Hi,

I just installed this addon and it is not generating files with logs inside `statamic-logger-YYYY-MM-DD.log` files. Locally it does, but when pushing the same config and env file live it is not working. Did I miss something / Any idea why? 

Environment
Application Name: hidden
Laravel Version: 10.48.11
PHP Version: 8.2.17
Composer Version: 2.7.7
Environment: production
Debug Mode: OFF
URL: hidden
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Cache: redis
Database: mysql
Logs: stack / daily, slack
Mail: mailgun
Queue: redis
Session: file

Statamic
Addons: 5
Sites: 2 (English, Dutch)
Stache Watcher: Disabled
Static Caching: half
Version: 5.4.0 PRO

Statamic Addons
aerni/advanced-seo: 2.5.0
heidkaemper/statamic-toolbar: 1.2.0
jacksleight/statamic-bard-texstyle: 3.2.2
mitydigital/statamic-logger: 2.1.1
statamic/collaboration: 1.0.0

**Comment by JorisOrangeStudio** [comment]
I thought is was maybe a license issue, so I bought the addon now for the live version and it is still returning an empty Utility view (because no log files are created). I haven't changed/added any ENV vars to change path or names. 

<img width="802" alt="Screenshot 2024-06-20 at 16 34 02" src="https://github.com/mitydigital/statamic-logger/assets/127202603/efe651f5-3407-4955-a2b2-0ed5445ea1b3">

**Comment by martyf** [comment]
Can you please look at your browser's console to see what errors are being output?

The view is generated using a Vue component, and I'm wondering if something is failing there as the styles aren't quite right either.

**Comment by JorisOrangeStudio** [comment]
Hi Marty,

In the console (and laravel.log) there are no errors present. I also tried to add a debug line after the Logger creation in the service provider. That is working fine when running composer dump-autoload, so the complete serviceprovider is executed. Otherwise there was also no Utility added. However still nog events are logged in a logs file and the view looks like above.

**Comment by martyf** [comment]
Can you please prepare step by step instructions for how to replicate this?

Or a repo of the code for me to try?

It sounds like a bigger issue than just Logger if the `laravel.log` file is empty too; and something on your server given you had it working locally.

**Comment by JorisOrangeStudio** [comment]
Can it be something with permissions for the statamic-logger.log files to be created/written? 
My current setup is `stack` with `daily` and `slack` error logs, those daily files are properly generated. 

The only step by step that I have is that i've installed in locally in the repository, then pushed it to live. There it installed the addon properly and also recognises the namespace. However no events are tracked. When running the list command it outputs all the events and listeners subscribed to, but still no events in a statamic-logger.log file.

**Comment by JorisOrangeStudio** [comment]
I found this error now when adding extra try catch in the Listener of User. I saw that the Queued Jobs for each listener were failing. We are using database users, maybe that can be the issue? 

```
[2024-06-21 08:42:04] production.ERROR: Call to undefined method App\Models\User::name() {"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method App\\Models\\User::name() at /home/ploi/www.example.com-deploy/www.example.com/20062024_143010/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:67)
[stacktrace]
#0 /home/ploi/www.example.com-deploy/www.example.com/20062024_143010/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException()
#1 /home/ploi/www.example.com-deploy/www.example.com/20062024_143010/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2334): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#2 /home/ploi/www.example.com-deploy/www.example.com/20062024_143010/vendor/mitydigital/statamic-logger/src/Listeners/User.php(32): Illuminate\\Database\\Eloquent\\Model->__call()
#3 /home/ploi/www.example.com-deploy/www.example.com/20062024_143010/vendor/mitydigital/statamic-logger/src/Abstracts/EventListener.php(37): MityDigital\\StatamicLogger\\Listeners\\User->data()
#4 /home/ploi/www.example.com-deploy/www.example.com/20062024_143010/vendor/mitydigital/statamic-logger/src/Abstracts/EventListener.php(19): MityDigital\\StatamicLogger\\Abstracts\\EventListener->buildLogEntry()
#5 /home/ploi/www.example.com-deploy/www.example.com/20062024_143010/vendor/laravel/framework/src/Illuminate/Events/CallQueuedListener.php(114): MityDigital\\StatamicLogger\\Abstracts\\EventListener->handle()
#6 /home/ploi/www.example.com-deploy/www.example.com/20062024_143010/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Events\\CallQueuedListener->handle()
#7 /home/ploi/www.example.com-deploy/www.example.com/20062024_143010/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
```

**Comment by martyf** [comment]
Thanks for debugging this one - I can confirm with a database, I can get the issue too.

I've put a fix in place to check for a `name()` method, a `name` property, or just set the ID as the 'name' as the fallback. 

I'll update the docs about this too.

**Comment by JorisOrangeStudio** [comment]
Hi @martyf,
Thanks for the new release! I've updated the addon but saw that the day after I installed it (21 June) no more logs were created. 
As you can see, the dropdown only contains the day that I installed the addon. Any idea why it is not logging anymore? 
![Screenshot 2024-06-25 at 09 08 40](https://github.com/mitydigital/statamic-logger/assets/127202603/0f2d26a4-b239-4140-a08e-e8ac83c6abd7)

I've checked the Jobs and they are running fine, no errors in the laravel.log. Again haven't changed any .env variables here. 
<img width="677" alt="Screenshot 2024-06-25 at 09 07 08" src="https://github.com/mitydigital/statamic-logger/assets/127202603/8ceeec72-eed1-4742-867c-c07e1198f00d">

Let me know how I can help with debugging, it is unfortunately not possible to share this repo. But feel free to ask all the details you need :)

**Comment by JorisOrangeStudio** [comment]
It looks like it is working now, no idea why it wasn't from 21 till 25, but now it makes a new log for today :)
